---

- name: Download grafana
  hosts: grafana_server
  become: yes

  tasks:
  - name: Download grafana
    get_url:
      url: https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb
      dest: /home/user/






